import fs from "node:fs";
import path from "node:path";

import { pascalCase } from "change-case";

import { generateVerifierCmd } from "./generate-verifier-cmd.js";
import { cmd, ROOT_DIR } from "../lib/cmd.js";
import type { AddCmdFn } from "../base-cli.js";
import { MAIN_CIRCUIT_FILE } from "../paths.js";

export async function exportVerifierCmd(): Promise<void> {
  const circuitPath = path.join(ROOT_DIR, MAIN_CIRCUIT_FILE);
  const fileData = path.parse(circuitPath);

  const contractsDir = path.join(ROOT_DIR, "..", "contracts", "src");
  if (!fs.existsSync(contractsDir)) {
    throw new Error(`Dir ${contractsDir} does not exist. This command only work when this repo is uses as submodule od zksync-sso.`);
  }

  const outDir = path.join(contractsDir, "autogenerated");

  await cmd(`mkdir -p ${outDir}`);

  const fileName = pascalCase(`${fileData.name}-verifier`) + ".sol";
  const out = path.join(outDir, fileName);

  await generateVerifierCmd(circuitPath, out);
  console.log(`Generated verifier at: ${out}`);
}

export const addExportVerifierCmd: AddCmdFn = (cli) => {
  return cli.command(
    "export-verifier",
    "exports verifier into right contracts folder",
    async () => {
      await exportVerifierCmd();
    });
};
