import fs from "node:fs";
import path from "node:path";
import { pascalCase } from "change-case";

import { generateVerifier } from "./generate-verifier.js";
import { ROOT_DIR } from "./lib/cmd.js";

export async function exportVerifierCmd(circuitPath: string): Promise<void> {
  const fileData = path.parse(circuitPath);

  const ourDir = path.join(ROOT_DIR, "..", "contracts", "src", "autogenerated");
  if (!fs.existsSync(ourDir)) {
    throw new Error(`Dir ${ourDir} does not exist. This command only work when this repo is uses as submodule od zksync-sso.`);
  }

  const fileName = pascalCase(`${fileData.name}-verifier`) + ".sol";
  const out = path.join(ourDir, fileName);

  await generateVerifier(circuitPath, out);
  console.log(`Generated verifier at: ${out}`);
}
