import fs from "node:fs";
import path from "node:path";

import { pascalCase } from "change-case";

import { generateVerifier } from "./generate-verifier.js";
import { cmd, ROOT_DIR } from "./lib/cmd.js";

export async function exportVerifierCmd(circuitPath: string): Promise<void> {
  const fileData = path.parse(circuitPath);

  const contractsDir = path.join(ROOT_DIR, "..", "contracts", "src");
  if (!fs.existsSync(contractsDir)) {
    throw new Error(`Dir ${contractsDir} does not exist. This command only work when this repo is uses as submodule od zksync-sso.`);
  }

  const outDir = path.join(contractsDir, "autogenerated");

  await cmd(`mkdir -p ${outDir}`);

  const fileName = pascalCase(`${fileData.name}-verifier`) + ".sol";
  const out = path.join(outDir, fileName);

  await generateVerifier(circuitPath, out);
  console.log(`Generated verifier at: ${out}`);
}
